services:

  web:
    build: .
    container_name: deploymentdemo
    command: gunicorn DeploymentDemo.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"

  celery:
    build: .
    container_name: deploymentdemo-celery
    command: celery -A DeploymentDemo worker --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis